version: '1.0'
name: master-pipeline
displayName: MasterPipeline
stages:
  - stage: 
    name: compile
    displayName: 编译
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        # 支持8.16.2、10.17.0、12.16.1、14.16.0、15.12.0五个版本
        nodeVersion: 14.16.0
        # 构建命令：安装依赖 -> 清除上次打包产物残留 -> 执行构建 【请根据项目实际产出进行填写】
        commands:
          - rm -rf node_modules docs/.vitepress/dist dist node-v18.19.0-linux-x64 node-v18.19.0-linux-x64.tar.xz
          - wget -q https://nodejs.org/dist/v18.19.0/node-v18.19.0-linux-x64.tar.xz
          - tar -xf node-v18.19.0-linux-x64.tar.xz
          - ./node-v18.19.0-linux-x64/bin/node -v
          - ./node-v18.19.0-linux-x64/bin/node ./node-v18.19.0-linux-x64/lib/node_modules/npm/bin/npm-cli.js -v
          - ./node-v18.19.0-linux-x64/bin/node ./node-v18.19.0-linux-x64/lib/node_modules/npm/bin/npm-cli.js install
          - ./node-v18.19.0-linux-x64/bin/node node_modules/vitepress/bin/vitepress.js build docs
          - test -d docs/.vitepress/dist
          - echo "AUTH_DEBUG: env keys (filtered):"
          - env | cut -d= -f1 | grep -E '(^GITEE|_GITEE|TOKEN|CRED|CREDENTIAL)' | sort | uniq
          - set +x
          - PICKED_USER_KEY=""
          - PICKED_TOKEN_KEY=""
          - USER=""
          - TOKEN=""
          - for k in GITEE_TOKEN_USERNAME GITEE_USERNAME GITEE_USER CRED_GITEE_TOKEN_USERNAME CREDENTIAL_GITEE_TOKEN_USERNAME; do v="$(eval "printf \"%s\" \"\${$k-}\"")"; if [ -n "$v" ]; then USER="$v"; PICKED_USER_KEY="$k"; break; fi; done
          - for k in GITEE_TOKEN_PASSWORD GITEE_TOKEN GITEE_PASSWORD GITEE_ACCESS_TOKEN GITEE_PERSONAL_ACCESS_TOKEN CRED_GITEE_TOKEN_PASSWORD CREDENTIAL_GITEE_TOKEN_PASSWORD; do v="$(eval "printf \"%s\" \"\${$k-}\"")"; if [ -n "$v" ]; then TOKEN="$v"; PICKED_TOKEN_KEY="$k"; break; fi; done
          - USER="${USER:-xheishou}"
          - TOKEN_LEN_BEFORE="$(printf "%s" "$TOKEN" | wc -c | tr -d ' ')"
          - TOKEN="$(printf "%s" "$TOKEN" | tr -d '\r\n')"
          - TOKEN_LEN_AFTER="$(printf "%s" "$TOKEN" | wc -c | tr -d ' ')"
          - test -n "$TOKEN" || (echo "Missing token in pipeline env. Please ensure Gitee Go 凭证管理里创建的凭证能注入到流水线（用户名/密码），或在流水线环境变量里提供 token。" && exit 1)
          - echo "AUTH_DEBUG: USER=${USER} USER_KEY=${PICKED_USER_KEY:-default} TOKEN_KEY=${PICKED_TOKEN_KEY:-none} TOKEN_LEN_BEFORE=${TOKEN_LEN_BEFORE} TOKEN_LEN_AFTER=${TOKEN_LEN_AFTER}"
          - DIST_TMP="$(mktemp -d)"
          - cp -a docs/.vitepress/dist/. "$DIST_TMP"/
          - git config user.name "gitee-go"
          - git config user.email "gitee-go@noreply"
          - git fetch origin pages || true
          - git checkout --orphan pages
          - find . -mindepth 1 -maxdepth 1 ! -name ".git" -exec rm -rf {} +
          - cp -a "$DIST_TMP"/. .
          - touch .nojekyll
          - git add -A
          - git commit -m "Deploy pages"
          - git remote set-url origin "https://gitee.com/xheishou/termux-x-wiki.git"
          - BASIC="$(printf "%s" "${USER}:${TOKEN}" | base64 | tr -d '\n')"
          - echo "AUTH_DEBUG: BASIC_LEN=$(printf "%s" "$BASIC" | wc -c | tr -d ' ')"
          - echo "AUTH_DEBUG: ls-remote pages (should succeed if token has write access):"
          - git -c http.extraHeader="Authorization: Basic ${BASIC}" ls-remote --heads origin pages || (echo "AUTH_DEBUG: ls-remote failed (auth/permission issue)" && exit 1)
          - git -c http.extraHeader="Authorization: Basic ${BASIC}" push -f origin pages
        # 非必填字段，开启后表示将构建产物暂存，但不会上传到制品库中，7天后自动清除
        artifacts:
            # 构建产物名字，作为产物的唯一标识可向下传递，支持自定义，默认为BUILD_ARTIFACT。在下游可以通过${BUILD_ARTIFACT}方式引用来获取构建物地址
          - name: BUILD_ARTIFACT
            # 构建产物获取路径，是指代码编译完毕之后构建物的所在路径
            path:
              - docs/.vitepress/dist
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        # 上游构建任务定义的产物名，默认BUILD_ARTIFACT
        dependArtifact: BUILD_ARTIFACT
        # 上传到制品库时的制品命名，默认output
        artifactName: output
        dependsOn: build_nodejs
  - stage: 
    name: release
    displayName: 发布
    steps:
      - step: publish@release_artifacts
        name: publish_release_artifacts
        displayName: '发布'
        # 上游上传制品任务的产出
        dependArtifact: output
        # 发布制品版本号
        version: '1.0.0.0'
        # 是否开启版本号自增，默认开启
        autoIncrement: true
triggers:
  push:
    branches:
      include:
        - master
