name: Termux-X Wiki Build & Deploy
displayName: 'Termux-X Wiki 自动构建与部署'
triggers:
  push:
    branches:
      - master

steps:
  # Gitee Go 目前对自定义镜像支持有限，还是需要回退到 shell 脚本手动安装 Node 18
  - step: build@nodejs
    name: build_site
    displayName: '构建 VitePress 站点'
    nodeVersion: 14.16.0 # 这是 Gitee 默认版本，我们必须手动升级
    commands:
      # 手动升级 Node.js 到 18.x
      - set -e
      - echo "Checking initial Node version..."
      - node -v
      - echo "Downloading Node.js 18..."
      - wget https://nodejs.org/dist/v18.19.0/node-v18.19.0-linux-x64.tar.xz
      - tar -xf node-v18.19.0-linux-x64.tar.xz
      - export PATH=$PWD/node-v18.19.0-linux-x64/bin:$PATH
      - echo "Verifying new Node version..."
      - node -v
      - npm -v
      # 开始构建
      - npm install
      - npm run docs:build
    artifacts:
      - name: dist
        path: docs/.vitepress/dist

  - step: deploy@pages
    name: deploy_pages
    displayName: '部署到 Gitee Pages'
    dependencies:
      - build_site
    # 如果自动部署失败，请手动配置 GITEE_TOKEN 并取消注释以下 block
    # commands:
    #   - cd docs/.vitepress/dist
    #   - git init
    #   - git checkout -b pages
    #   - git add .
    #   - git config user.name "Gitee Go Bot"
    #   - git config user.email "bot@gitee.com"
    #   - git commit -m "Auto deploy"
    #   - git push -f "https://${GITEE_TOKEN}@gitee.com/xheishou/termux-x-wiki.git" pages
