name: Termux-X Wiki Build & Deploy
displayName: 'Termux-X Wiki 自动构建与部署'
triggers:
  push:
    branches:
      - master

steps:
  - name: build_site
    displayName: '构建 VitePress 站点'
    # 尝试直接使用 Node.js 18 的 Docker 镜像，避开 Gitee Go 默认插件的 Node 14 限制
    image: node:18
    commands:
      - node -v
      - npm install
      - npm run docs:build
    artifacts:
      - name: dist
        path: docs/.vitepress/dist

  - step: deploy@pages
    name: deploy_pages
    displayName: '部署到 Gitee Pages'
    dependencies:
      - build_site
    # 如果自动部署失败，请手动配置 GITEE_TOKEN 并取消注释以下 block
    # commands:
    #   - cd docs/.vitepress/dist
    #   - git init
    #   - git checkout -b pages
    #   - git add .
    #   - git config user.name "Gitee Go Bot"
    #   - git config user.email "bot@gitee.com"
    #   - git commit -m "Auto deploy"
    #   - git push -f "https://${GITEE_TOKEN}@gitee.com/xheishou/termux-x-wiki.git" pages
