name: Termux-X Wiki Build & Deploy
displayName: 'Termux-X Wiki 自动构建与部署'
triggers:
  push:
    branches:
      - master

steps:
  - name: build_site
    displayName: '构建 VitePress 站点'
    # 使用官方 Node.js 18 镜像
    image: node:18
    commands:
      # 1. 强制清理（可选，视 CI 环境是否持久化而定）
      - rm -rf node_modules package-lock.json dist

      # 2. 安装依赖
      - npm install

      # 3. 执行构建 (直接调用 vitepress 二进制文件)
      # 避开 npm run 可能存在的环境劫持
      - ./node_modules/.bin/vitepress build docs
    artifacts:
      - name: dist
        path: docs/.vitepress/dist

  - step: deploy@pages
    name: deploy_pages
    displayName: '部署到 Gitee Pages'
    dependencies:
      - build_site
