name: Termux-X Wiki Build & Deploy
displayName: 'Termux-X Wiki 自动构建与部署'
triggers:
  push:
    branches:
      - master

steps:
  - step: build@nodejs
    name: build_site
    displayName: '构建 VitePress 站点'
    nodeVersion: 14.16.0
    commands:
      # 清理环境
      - set -e
      - rm -rf node_modules package-lock.json

      # 手动安装 Node.js 18
      - echo "Downloading Node.js 18..."
      - wget -q https://nodejs.org/dist/v18.19.0/node-v18.19.0-linux-x64.tar.xz
      - tar -xf node-v18.19.0-linux-x64.tar.xz
      
      # 设置环境变量，确保后续命令优先使用新版 Node
      - export NODE_HOME=$PWD/node-v18.19.0-linux-x64
      - export PATH=$NODE_HOME/bin:$PATH
      
      # 验证版本
      - echo "Node version:"
      - node -v
      - echo "NPM version:"
      - npm -v

      # 安装依赖 (显式使用新版 npm)
      - npm install

      # 执行构建 (直接调用 vitepress 二进制文件，避免 npm run 的 shell 环境问题)
      - ./node_modules/.bin/vitepress build docs
    artifacts:
      - name: dist
        path: docs/.vitepress/dist

  - step: deploy@pages
    name: deploy_pages
    displayName: '部署到 Gitee Pages'
    dependencies:
      - build_site
