name: Termux-X Wiki Build & Deploy
displayName: 'Termux-X Wiki 自动构建与部署'
triggers:
  push:
    branches:
      - master

steps:
  - step: build@nodejs
    name: build_site
    displayName: '构建 VitePress 站点'
    nodeVersion: 18
    commands:
      - npm install
      - npm run docs:build
    artifacts:
      - name: dist
        path: docs/.vitepress/dist

  - step: deploy@pages
    name: deploy_pages
    displayName: '部署到 Gitee Pages'
    dependencies:
      - build_site
    # 注意：使用 Gitee Go 进行 Pages 部署通常需要以下配置
    # 1. 确保已开通 Gitee Pages 服务
    # 2. 此步骤会尝试将构建产物部署到 Pages
    # 如果您使用的是 Gitee Go 的官方 Pages 插件，请在网页端流水线配置中确认插件版本和参数
    # 以下是一个通用的 Shell 部署脚本示例，适用于手动配置了 GITEE_TOKEN 的情况
    # commands:
    #   - cd docs/.vitepress/dist
    #   - git init
    #   - git checkout -b pages
    #   - git add .
    #   - git config user.name "Gitee Go Bot"
    #   - git config user.email "bot@gitee.com"
    #   - git commit -m "Auto deploy"
    #   - git push -f "https://${GITEE_TOKEN}@gitee.com/xheishou/termux-x-wiki.git" pages
